name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: testing
      - name: Install dependencies
        run: |
          conda install -c conda-forge grblas networkx scipy pytest coverage black flake8 coveralls
          pip install -e .
      - name: Style checks
        run: |
          flake8
          black . --check --diff
      - name: PyTest
        run: |
          coverage run --branch -m pytest
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version}}/${{ matrix.os }}
          COVERALLS_PARALLEL: true
        run: |
          coverage report --show-missing
          coveralls --service=github

  finish:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: finishing
      - name: Update env
        run: conda install -c conda-forge coveralls
      - name: Coveralls finished
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --finish
